// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package storeproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessType int32

const (
	BusinessType_Sole        BusinessType = 0
	BusinessType_Partnership BusinessType = 1
	BusinessType_Company     BusinessType = 2
)

var BusinessType_name = map[int32]string{
	0: "Sole",
	1: "Partnership",
	2: "Company",
}

var BusinessType_value = map[string]int32{
	"Sole":        0,
	"Partnership": 1,
	"Company":     2,
}

func (x BusinessType) String() string {
	return proto.EnumName(BusinessType_name, int32(x))
}

func (BusinessType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

type State int32

const (
	State_Kuala_Lumpur    State = 0
	State_Selangor        State = 1
	State_Putrajaya       State = 2
	State_Perak           State = 3
	State_Negeri_Sembilan State = 4
	State_Malacca         State = 5
	State_Johor           State = 6
	State_Penang          State = 7
	State_Pahang          State = 8
	State_Kedah           State = 9
	State_Perlis          State = 10
	State_Terrenganu      State = 11
	State_Kelatan         State = 12
	State_Sarawak         State = 13
	State_Sabah           State = 14
	State_Labuan          State = 15
)

var State_name = map[int32]string{
	0:  "Kuala_Lumpur",
	1:  "Selangor",
	2:  "Putrajaya",
	3:  "Perak",
	4:  "Negeri_Sembilan",
	5:  "Malacca",
	6:  "Johor",
	7:  "Penang",
	8:  "Pahang",
	9:  "Kedah",
	10: "Perlis",
	11: "Terrenganu",
	12: "Kelatan",
	13: "Sarawak",
	14: "Sabah",
	15: "Labuan",
}

var State_value = map[string]int32{
	"Kuala_Lumpur":    0,
	"Selangor":        1,
	"Putrajaya":       2,
	"Perak":           3,
	"Negeri_Sembilan": 4,
	"Malacca":         5,
	"Johor":           6,
	"Penang":          7,
	"Pahang":          8,
	"Kedah":           9,
	"Perlis":          10,
	"Terrenganu":      11,
	"Kelatan":         12,
	"Sarawak":         13,
	"Sabah":           14,
	"Labuan":          15,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

type GetAccount struct {
	AccountType          string   `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccount) Reset()         { *m = GetAccount{} }
func (m *GetAccount) String() string { return proto.CompactTextString(m) }
func (*GetAccount) ProtoMessage()    {}
func (*GetAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *GetAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccount.Unmarshal(m, b)
}
func (m *GetAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccount.Marshal(b, m, deterministic)
}
func (m *GetAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccount.Merge(m, src)
}
func (m *GetAccount) XXX_Size() int {
	return xxx_messageInfo_GetAccount.Size(m)
}
func (m *GetAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccount.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccount proto.InternalMessageInfo

func (m *GetAccount) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

type Acknowledgement struct {
	Acknowledgement      string   `protobuf:"bytes,1,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetAcknowledgement() string {
	if m != nil {
		return m.Acknowledgement
	}
	return ""
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode           string   `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	State                State    `protobuf:"varint,4,opt,name=state,proto3,enum=storeproto.State" json:"state,omitempty"`
	Lat                  int32    `protobuf:"varint,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  int32    `protobuf:"varint,6,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Address) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Kuala_Lumpur
}

func (m *Address) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Address) GetLon() int32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type PIC struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PIC) Reset()         { *m = PIC{} }
func (m *PIC) String() string { return proto.CompactTextString(m) }
func (*PIC) ProtoMessage()    {}
func (*PIC) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *PIC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PIC.Unmarshal(m, b)
}
func (m *PIC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PIC.Marshal(b, m, deterministic)
}
func (m *PIC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PIC.Merge(m, src)
}
func (m *PIC) XXX_Size() int {
	return xxx_messageInfo_PIC.Size(m)
}
func (m *PIC) XXX_DiscardUnknown() {
	xxx_messageInfo_PIC.DiscardUnknown(m)
}

var xxx_messageInfo_PIC proto.InternalMessageInfo

func (m *PIC) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PIC) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PIC) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PIC) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Business struct {
	Id                     string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Page                   string       `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	BusinessType           BusinessType `protobuf:"varint,4,opt,name=business_type,json=businessType,proto3,enum=storeproto.BusinessType" json:"business_type,omitempty"`
	Category               string       `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	SsmName                string       `protobuf:"bytes,6,opt,name=ssm_name,json=ssmName,proto3" json:"ssm_name,omitempty"`
	SsmResgistrationNumber string       `protobuf:"bytes,7,opt,name=ssm_resgistration_number,json=ssmResgistrationNumber,proto3" json:"ssm_resgistration_number,omitempty"`
	Address                *Address     `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Pic                    *PIC         `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Inventory              bool         `protobuf:"varint,10,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}     `json:"-"`
	XXX_unrecognized       []byte       `json:"-"`
	XXX_sizecache          int32        `json:"-"`
}

func (m *Business) Reset()         { *m = Business{} }
func (m *Business) String() string { return proto.CompactTextString(m) }
func (*Business) ProtoMessage()    {}
func (*Business) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *Business) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Business.Unmarshal(m, b)
}
func (m *Business) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Business.Marshal(b, m, deterministic)
}
func (m *Business) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Business.Merge(m, src)
}
func (m *Business) XXX_Size() int {
	return xxx_messageInfo_Business.Size(m)
}
func (m *Business) XXX_DiscardUnknown() {
	xxx_messageInfo_Business.DiscardUnknown(m)
}

var xxx_messageInfo_Business proto.InternalMessageInfo

func (m *Business) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Business) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Business) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Business) GetBusinessType() BusinessType {
	if m != nil {
		return m.BusinessType
	}
	return BusinessType_Sole
}

func (m *Business) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Business) GetSsmName() string {
	if m != nil {
		return m.SsmName
	}
	return ""
}

func (m *Business) GetSsmResgistrationNumber() string {
	if m != nil {
		return m.SsmResgistrationNumber
	}
	return ""
}

func (m *Business) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Business) GetPic() *PIC {
	if m != nil {
		return m.Pic
	}
	return nil
}

func (m *Business) GetInventory() bool {
	if m != nil {
		return m.Inventory
	}
	return false
}

type Outlet struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Pic                  *PIC     `protobuf:"bytes,4,opt,name=pic,proto3" json:"pic,omitempty"`
	Inventory            bool     `protobuf:"varint,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	BusinessId           string   `protobuf:"bytes,6,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outlet) Reset()         { *m = Outlet{} }
func (m *Outlet) String() string { return proto.CompactTextString(m) }
func (*Outlet) ProtoMessage()    {}
func (*Outlet) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *Outlet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outlet.Unmarshal(m, b)
}
func (m *Outlet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outlet.Marshal(b, m, deterministic)
}
func (m *Outlet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outlet.Merge(m, src)
}
func (m *Outlet) XXX_Size() int {
	return xxx_messageInfo_Outlet.Size(m)
}
func (m *Outlet) XXX_DiscardUnknown() {
	xxx_messageInfo_Outlet.DiscardUnknown(m)
}

var xxx_messageInfo_Outlet proto.InternalMessageInfo

func (m *Outlet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Outlet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Outlet) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Outlet) GetPic() *PIC {
	if m != nil {
		return m.Pic
	}
	return nil
}

func (m *Outlet) GetInventory() bool {
	if m != nil {
		return m.Inventory
	}
	return false
}

func (m *Outlet) GetBusinessId() string {
	if m != nil {
		return m.BusinessId
	}
	return ""
}

type Outlets struct {
	Outlets              []*Outlet `protobuf:"bytes,1,rep,name=outlets,proto3" json:"outlets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Outlets) Reset()         { *m = Outlets{} }
func (m *Outlets) String() string { return proto.CompactTextString(m) }
func (*Outlets) ProtoMessage()    {}
func (*Outlets) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{6}
}

func (m *Outlets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outlets.Unmarshal(m, b)
}
func (m *Outlets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outlets.Marshal(b, m, deterministic)
}
func (m *Outlets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outlets.Merge(m, src)
}
func (m *Outlets) XXX_Size() int {
	return xxx_messageInfo_Outlets.Size(m)
}
func (m *Outlets) XXX_DiscardUnknown() {
	xxx_messageInfo_Outlets.DiscardUnknown(m)
}

var xxx_messageInfo_Outlets proto.InternalMessageInfo

func (m *Outlets) GetOutlets() []*Outlet {
	if m != nil {
		return m.Outlets
	}
	return nil
}

type SignUpBusiness struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Business             *Business `protobuf:"bytes,3,opt,name=business,proto3" json:"business,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignUpBusiness) Reset()         { *m = SignUpBusiness{} }
func (m *SignUpBusiness) String() string { return proto.CompactTextString(m) }
func (*SignUpBusiness) ProtoMessage()    {}
func (*SignUpBusiness) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{7}
}

func (m *SignUpBusiness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpBusiness.Unmarshal(m, b)
}
func (m *SignUpBusiness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpBusiness.Marshal(b, m, deterministic)
}
func (m *SignUpBusiness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpBusiness.Merge(m, src)
}
func (m *SignUpBusiness) XXX_Size() int {
	return xxx_messageInfo_SignUpBusiness.Size(m)
}
func (m *SignUpBusiness) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpBusiness.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpBusiness proto.InternalMessageInfo

func (m *SignUpBusiness) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpBusiness) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpBusiness) GetBusiness() *Business {
	if m != nil {
		return m.Business
	}
	return nil
}

type CreateOutlet struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Outlet               *Outlet  `protobuf:"bytes,3,opt,name=outlet,proto3" json:"outlet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOutlet) Reset()         { *m = CreateOutlet{} }
func (m *CreateOutlet) String() string { return proto.CompactTextString(m) }
func (*CreateOutlet) ProtoMessage()    {}
func (*CreateOutlet) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{8}
}

func (m *CreateOutlet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOutlet.Unmarshal(m, b)
}
func (m *CreateOutlet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOutlet.Marshal(b, m, deterministic)
}
func (m *CreateOutlet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOutlet.Merge(m, src)
}
func (m *CreateOutlet) XXX_Size() int {
	return xxx_messageInfo_CreateOutlet.Size(m)
}
func (m *CreateOutlet) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOutlet.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOutlet proto.InternalMessageInfo

func (m *CreateOutlet) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateOutlet) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateOutlet) GetOutlet() *Outlet {
	if m != nil {
		return m.Outlet
	}
	return nil
}

func init() {
	proto.RegisterEnum("storeproto.BusinessType", BusinessType_name, BusinessType_value)
	proto.RegisterEnum("storeproto.State", State_name, State_value)
	proto.RegisterType((*GetAccount)(nil), "storeproto.GetAccount")
	proto.RegisterType((*Acknowledgement)(nil), "storeproto.Acknowledgement")
	proto.RegisterType((*Address)(nil), "storeproto.Address")
	proto.RegisterType((*PIC)(nil), "storeproto.PIC")
	proto.RegisterType((*Business)(nil), "storeproto.Business")
	proto.RegisterType((*Outlet)(nil), "storeproto.Outlet")
	proto.RegisterType((*Outlets)(nil), "storeproto.Outlets")
	proto.RegisterType((*SignUpBusiness)(nil), "storeproto.SignUpBusiness")
	proto.RegisterType((*CreateOutlet)(nil), "storeproto.CreateOutlet")
}

func init() {
	proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc)
}

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 1197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x8e, 0xdb, 0xc4,
	0x17, 0xae, 0x93, 0xcd, 0xbf, 0x93, 0xec, 0xae, 0x3b, 0xbb, 0xda, 0x9f, 0xeb, 0xf6, 0x47, 0x5d,
	0xdf, 0x34, 0x5a, 0xb5, 0x49, 0x59, 0x2a, 0x40, 0xad, 0x90, 0xd8, 0x8d, 0x10, 0x2a, 0x2d, 0x25,
	0x4a, 0x8a, 0x04, 0x42, 0x28, 0x4c, 0xec, 0x53, 0xc7, 0xad, 0x3d, 0x63, 0x66, 0xc6, 0xdd, 0x06,
	0xc4, 0x0d, 0x2f, 0x80, 0x04, 0x77, 0xdc, 0xf3, 0x18, 0x88, 0x87, 0xe0, 0x9e, 0x0b, 0xc4, 0x25,
	0x0f, 0x81, 0x3c, 0xb6, 0xb3, 0xde, 0x6e, 0xd8, 0xae, 0xb8, 0xca, 0x39, 0xdf, 0x39, 0x39, 0xe7,
	0x9b, 0x6f, 0xce, 0xf8, 0x40, 0x57, 0x2a, 0x2e, 0x70, 0x90, 0x08, 0xae, 0x38, 0x01, 0xed, 0x68,
	0xdb, 0xbe, 0x16, 0x70, 0x1e, 0x44, 0x38, 0xa4, 0x49, 0x38, 0xa4, 0x8c, 0x71, 0x45, 0x55, 0xc8,
	0x99, 0xcc, 0x33, 0xed, 0x5b, 0xfa, 0xc7, 0xbb, 0x1d, 0x20, 0xbb, 0x2d, 0x8f, 0x69, 0x10, 0xa0,
	0x18, 0xf2, 0x44, 0x67, 0xac, 0xc9, 0xbe, 0x5a, 0xd4, 0xd2, 0xde, 0x3c, 0x7d, 0x3a, 0xc4, 0x38,
	0x51, 0xcb, 0x3c, 0xe8, 0x0e, 0x01, 0x3e, 0x44, 0x75, 0xe8, 0x79, 0x3c, 0x65, 0x8a, 0xdc, 0x80,
	0x1e, 0xcd, 0xcd, 0x99, 0x5a, 0x26, 0x68, 0x19, 0x8e, 0xd1, 0xef, 0x4c, 0xba, 0x05, 0xf6, 0x64,
	0x99, 0xa0, 0x7b, 0x1f, 0xb6, 0x0f, 0xbd, 0xe7, 0x8c, 0x1f, 0x47, 0xe8, 0x07, 0x18, 0x23, 0x53,
	0xa4, 0x0f, 0xdb, 0xf4, 0x34, 0x54, 0xfc, 0xf1, 0x55, 0xd8, 0xfd, 0xc5, 0x80, 0xd6, 0xa1, 0xef,
	0x0b, 0x94, 0x92, 0x58, 0xd0, 0xa2, 0xb9, 0x59, 0x64, 0x97, 0x2e, 0x21, 0xb0, 0xe1, 0x85, 0x6a,
	0x69, 0xd5, 0x34, 0xac, 0x6d, 0x72, 0x1d, 0xba, 0x09, 0x97, 0x8a, 0x46, 0x33, 0x8f, 0xfb, 0x68,
	0xd5, 0x75, 0x08, 0x72, 0x68, 0xc4, 0x7d, 0x24, 0x37, 0xa1, 0x21, 0x15, 0x55, 0x68, 0x6d, 0x38,
	0x46, 0x7f, 0xeb, 0xe0, 0xf2, 0xe0, 0x44, 0xcd, 0xc1, 0x34, 0x0b, 0x4c, 0xf2, 0x38, 0x31, 0xa1,
	0x1e, 0x51, 0x65, 0x35, 0x1c, 0xa3, 0xdf, 0x98, 0x64, 0xa6, 0x46, 0x38, 0xb3, 0x9a, 0x05, 0xc2,
	0x99, 0x1b, 0x43, 0x7d, 0xfc, 0x60, 0x44, 0xfe, 0x0f, 0xf0, 0x34, 0x14, 0x52, 0xcd, 0x18, 0x8d,
	0x4b, 0x31, 0x3a, 0x1a, 0x79, 0x4c, 0x63, 0x24, 0x57, 0xa1, 0x13, 0xd1, 0x32, 0x9a, 0x93, 0x6d,
	0x67, 0x80, 0x0e, 0xee, 0x42, 0x03, 0x63, 0x1a, 0x46, 0x05, 0xd5, 0xdc, 0xc9, 0xd0, 0x64, 0xc1,
	0x59, 0xce, 0xb2, 0x33, 0xc9, 0x1d, 0xf7, 0xcf, 0x1a, 0xb4, 0x8f, 0x52, 0x19, 0xb2, 0xec, 0xf4,
	0x5b, 0x50, 0x0b, 0xfd, 0xa2, 0x59, 0x2d, 0xf4, 0x33, 0x35, 0x2a, 0x0d, 0xb4, 0x9d, 0x61, 0x09,
	0x0d, 0x4a, 0x19, 0xb4, 0x4d, 0xde, 0x83, 0xcd, 0x79, 0x51, 0x23, 0xbf, 0xbc, 0x5c, 0x08, 0xab,
	0x2a, 0x44, 0xd9, 0x24, 0xbb, 0xc9, 0x49, 0x6f, 0x5e, 0xf1, 0x88, 0x0d, 0x6d, 0x8f, 0x2a, 0x0c,
	0xb8, 0x58, 0x6a, 0x6d, 0x3a, 0x93, 0x95, 0x4f, 0xae, 0x40, 0x5b, 0xca, 0x38, 0x3f, 0x67, 0x33,
	0xbf, 0x2b, 0x29, 0x63, 0x7d, 0xcc, 0x77, 0xc1, 0xca, 0x42, 0x02, 0x65, 0x10, 0x4a, 0x25, 0xf4,
	0xe0, 0xcd, 0x58, 0x1a, 0xcf, 0x51, 0x58, 0x2d, 0x9d, 0xba, 0x27, 0x65, 0x3c, 0xa9, 0x86, 0x1f,
	0xeb, 0x28, 0xb9, 0x7d, 0x72, 0xff, 0x6d, 0xc7, 0xe8, 0x77, 0x0f, 0x76, 0xaa, 0x4c, 0x8b, 0x29,
	0x39, 0x19, 0x8a, 0x1b, 0x50, 0x4f, 0x42, 0xcf, 0xea, 0xe8, 0xd4, 0xed, 0x6a, 0xea, 0xf8, 0xc1,
	0x68, 0x92, 0xc5, 0xc8, 0x35, 0xe8, 0x84, 0xec, 0x05, 0x32, 0x95, 0x9d, 0x01, 0x1c, 0xa3, 0xdf,
	0x9e, 0x9c, 0x00, 0xee, 0xaf, 0x06, 0x34, 0x3f, 0x49, 0x55, 0x84, 0xea, 0x42, 0x12, 0x57, 0xe8,
	0xd5, 0x2f, 0x4e, 0x6f, 0xe3, 0xa2, 0xf4, 0x1a, 0xaf, 0xd0, 0xcb, 0x06, 0x7c, 0x75, 0x7d, 0xa1,
	0x5f, 0xc8, 0x0c, 0x25, 0xf4, 0xc0, 0x77, 0xdf, 0x81, 0x56, 0x4e, 0x5f, 0x92, 0x5b, 0xd0, 0xe2,
	0xb9, 0x69, 0x19, 0x4e, 0xbd, 0xdf, 0x3d, 0x20, 0xd5, 0x86, 0x79, 0xd6, 0xa4, 0x4c, 0x71, 0xbf,
	0x81, 0xad, 0x69, 0x18, 0xb0, 0x4f, 0x93, 0xd5, 0x88, 0xd9, 0xd0, 0x4e, 0x25, 0x8a, 0xca, 0x54,
	0xaf, 0xfc, 0x2c, 0x96, 0x50, 0x29, 0x8f, 0xb9, 0xf0, 0xcb, 0x99, 0x2e, 0x7d, 0x72, 0x07, 0xda,
	0x25, 0xa1, 0x42, 0x94, 0xdd, 0x75, 0xd3, 0x35, 0x59, 0x65, 0xb9, 0x02, 0x7a, 0x23, 0x81, 0x54,
	0x61, 0xa1, 0xfc, 0x7f, 0xed, 0xbc, 0x0f, 0xcd, 0xfc, 0x38, 0x45, 0xdf, 0x75, 0x07, 0x2e, 0x32,
	0xf6, 0xdf, 0x86, 0x5e, 0x75, 0xce, 0x49, 0x1b, 0x36, 0xa6, 0x3c, 0x42, 0xf3, 0x12, 0xd9, 0x86,
	0xee, 0x98, 0x0a, 0xc5, 0x50, 0xc8, 0x45, 0x98, 0x98, 0x06, 0xe9, 0x42, 0x6b, 0xc4, 0xe3, 0x84,
	0xb2, 0xa5, 0x59, 0xdb, 0xff, 0xc3, 0x80, 0xc6, 0xb4, 0xf8, 0x44, 0xf4, 0x1e, 0xa6, 0x34, 0xa2,
	0xb3, 0x47, 0x69, 0x9c, 0xa4, 0xc2, 0xbc, 0x44, 0x7a, 0xd0, 0x9e, 0x62, 0x44, 0x59, 0xc0, 0x85,
	0x69, 0x90, 0x4d, 0xe8, 0x8c, 0x53, 0x25, 0xe8, 0x33, 0xba, 0xa4, 0x66, 0x8d, 0x74, 0xa0, 0x31,
	0x46, 0x41, 0x9f, 0x9b, 0x75, 0xb2, 0x03, 0xdb, 0x8f, 0x31, 0x40, 0x11, 0xce, 0xa6, 0x18, 0xcf,
	0xc3, 0x88, 0x32, 0x73, 0x23, 0xeb, 0xf2, 0x31, 0x8d, 0xa8, 0xe7, 0x51, 0xb3, 0x91, 0x25, 0x7f,
	0xc4, 0x17, 0x5c, 0x98, 0x4d, 0x02, 0xd0, 0x1c, 0x23, 0xa3, 0x2c, 0x30, 0x5b, 0xda, 0xa6, 0x8b,
	0xcc, 0x6e, 0x67, 0x29, 0x0f, 0xd1, 0xa7, 0x0b, 0xb3, 0x93, 0xa7, 0x88, 0x28, 0x94, 0x26, 0x90,
	0x2d, 0x80, 0x27, 0x28, 0x04, 0xb2, 0x80, 0xb2, 0xd4, 0xec, 0x66, 0x65, 0x1f, 0x62, 0x44, 0x15,
	0x65, 0x66, 0x2f, 0x73, 0xa6, 0x54, 0xd0, 0x63, 0xfa, 0xdc, 0xdc, 0xcc, 0x0a, 0x4c, 0xe9, 0x9c,
	0x2e, 0xcc, 0xad, 0xac, 0xc0, 0x23, 0x3a, 0x4f, 0x29, 0x33, 0xb7, 0x0f, 0x7e, 0x68, 0x42, 0x6f,
	0x9a, 0xc9, 0x36, 0x45, 0xf1, 0x22, 0xf4, 0x90, 0x50, 0x68, 0x4a, 0x3d, 0x19, 0xc4, 0x3e, 0xf5,
	0xb9, 0x3c, 0x35, 0x2d, 0xf6, 0xd5, 0x53, 0x83, 0xff, 0xca, 0x17, 0xfd, 0x8d, 0xef, 0x7f, 0xff,
	0xeb, 0xa7, 0x9a, 0xe5, 0xee, 0xe8, 0x55, 0xa5, 0x13, 0x87, 0xe5, 0xed, 0xdf, 0x33, 0xf6, 0xc9,
	0x67, 0x00, 0xc1, 0xc9, 0x7e, 0xd9, 0x1b, 0xe4, 0xbb, 0x68, 0x50, 0xee, 0xa2, 0xc1, 0x07, 0xd9,
	0x2e, 0xb2, 0xf7, 0xaa, 0x2d, 0x4e, 0xf6, 0x91, 0x6b, 0xeb, 0xea, 0xbb, 0x84, 0x54, 0xaa, 0x17,
	0xcb, 0x88, 0x7c, 0x01, 0xdd, 0x00, 0xd5, 0x6a, 0xa6, 0xd7, 0x4e, 0xa2, 0xbd, 0x16, 0x75, 0x1d,
	0x5d, 0xd6, 0x26, 0xd6, 0x1a, 0xd2, 0xc3, 0x6f, 0x43, 0xff, 0x3b, 0xe2, 0xc1, 0x56, 0x9a, 0xf8,
	0x54, 0xe1, 0x6b, 0xea, 0x5f, 0x44, 0x1b, 0xfb, 0xdf, 0xb4, 0xf9, 0x0a, 0x7a, 0x5e, 0xf5, 0x71,
	0x9c, 0xfa, 0x54, 0x57, 0x9f, 0xcd, 0xf9, 0x6d, 0xae, 0xe8, 0x36, 0x3b, 0xee, 0xe5, 0x4a, 0x9b,
	0xfc, 0x29, 0x90, 0x29, 0x74, 0x02, 0x54, 0x45, 0xf9, 0x35, 0x6f, 0xc6, 0x5e, 0x83, 0x95, 0xb4,
	0xc9, 0xde, 0x99, 0x7a, 0xb9, 0x36, 0x5f, 0x42, 0x2f, 0xd7, 0xe6, 0x9c, 0xba, 0xe7, 0x12, 0xbe,
	0xa6, 0x1b, 0xec, 0xd9, 0x67, 0x09, 0x67, 0xaa, 0x3c, 0x83, 0xdd, 0x15, 0x67, 0x79, 0xb4, 0x7c,
	0xcd, 0x05, 0xec, 0x9c, 0x6d, 0x2e, 0xdd, 0x9b, 0xba, 0xc1, 0x0d, 0x72, 0x7d, 0x8d, 0xf0, 0xb3,
	0xca, 0x51, 0x8e, 0xfe, 0x36, 0x7e, 0x3c, 0xfc, 0xcd, 0x20, 0x9f, 0xc3, 0xa6, 0x7e, 0x17, 0x8e,
	0xcc, 0x1f, 0x86, 0x3b, 0x82, 0xbd, 0x00, 0x55, 0xa8, 0xbe, 0x46, 0xcf, 0x91, 0xd5, 0x08, 0xd9,
	0x5d, 0x28, 0x95, 0xc8, 0x7b, 0xc3, 0x61, 0x19, 0x1f, 0x78, 0x3c, 0xb6, 0x77, 0x8e, 0x5f, 0x0e,
	0x46, 0x0b, 0xc4, 0xf7, 0x33, 0xb4, 0x00, 0x0f, 0xea, 0x6f, 0x0e, 0xee, 0xec, 0x1b, 0xb5, 0x03,
	0x93, 0x26, 0x49, 0x14, 0x7a, 0x7a, 0xf7, 0x0d, 0x9f, 0x49, 0xce, 0xee, 0x9d, 0x41, 0x26, 0xf7,
	0xa1, 0x7e, 0xf7, 0xce, 0x5d, 0x72, 0x17, 0xf6, 0x27, 0xa8, 0x52, 0xc1, 0xd0, 0x77, 0x8e, 0x17,
	0xc8, 0x1c, 0xb5, 0x40, 0x47, 0xa0, 0xe4, 0xa9, 0xf0, 0xd0, 0xf1, 0x39, 0x4a, 0x87, 0x71, 0xe5,
	0xe0, 0xcb, 0x50, 0xaa, 0x01, 0x69, 0xc2, 0xc6, 0xcf, 0x35, 0xa3, 0x05, 0xff, 0xf3, 0x78, 0x3c,
	0x58, 0xf1, 0x99, 0xae, 0xf4, 0x38, 0x3a, 0xf5, 0xda, 0xc7, 0xc6, 0xbc, 0xa9, 0xe1, 0xb7, 0xfe,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x35, 0x43, 0x1c, 0x77, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	SignUp(ctx context.Context, in *SignUpBusiness, opts ...grpc.CallOption) (*Acknowledgement, error)
	GetAccount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAccount, error)
	GetBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Business, error)
	UpdateBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Acknowledgement, error)
	CreateOutlet(ctx context.Context, in *CreateOutlet, opts ...grpc.CallOption) (*Acknowledgement, error)
	GetOutlet(ctx context.Context, in *Outlet, opts ...grpc.CallOption) (*Outlet, error)
	UpdateOutlet(ctx context.Context, in *Outlet, opts ...grpc.CallOption) (*Acknowledgement, error)
	GetOutletsByBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Outlets, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) SignUp(ctx context.Context, in *SignUpBusiness, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/signUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetAccount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAccount, error) {
	out := new(GetAccount)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/getAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Business, error) {
	out := new(Business)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/getBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/updateBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) CreateOutlet(ctx context.Context, in *CreateOutlet, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/createOutlet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetOutlet(ctx context.Context, in *Outlet, opts ...grpc.CallOption) (*Outlet, error) {
	out := new(Outlet)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/getOutlet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateOutlet(ctx context.Context, in *Outlet, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/updateOutlet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetOutletsByBusiness(ctx context.Context, in *Business, opts ...grpc.CallOption) (*Outlets, error) {
	out := new(Outlets)
	err := c.cc.Invoke(ctx, "/storeproto.StoreService/getOutletsByBusiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	SignUp(context.Context, *SignUpBusiness) (*Acknowledgement, error)
	GetAccount(context.Context, *empty.Empty) (*GetAccount, error)
	GetBusiness(context.Context, *Business) (*Business, error)
	UpdateBusiness(context.Context, *Business) (*Acknowledgement, error)
	CreateOutlet(context.Context, *CreateOutlet) (*Acknowledgement, error)
	GetOutlet(context.Context, *Outlet) (*Outlet, error)
	UpdateOutlet(context.Context, *Outlet) (*Acknowledgement, error)
	GetOutletsByBusiness(context.Context, *Business) (*Outlets, error)
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) SignUp(ctx context.Context, req *SignUpBusiness) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedStoreServiceServer) GetAccount(ctx context.Context, req *empty.Empty) (*GetAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedStoreServiceServer) GetBusiness(ctx context.Context, req *Business) (*Business, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusiness not implemented")
}
func (*UnimplementedStoreServiceServer) UpdateBusiness(ctx context.Context, req *Business) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusiness not implemented")
}
func (*UnimplementedStoreServiceServer) CreateOutlet(ctx context.Context, req *CreateOutlet) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOutlet not implemented")
}
func (*UnimplementedStoreServiceServer) GetOutlet(ctx context.Context, req *Outlet) (*Outlet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutlet not implemented")
}
func (*UnimplementedStoreServiceServer) UpdateOutlet(ctx context.Context, req *Outlet) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOutlet not implemented")
}
func (*UnimplementedStoreServiceServer) GetOutletsByBusiness(ctx context.Context, req *Business) (*Outlets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutletsByBusiness not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpBusiness)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SignUp(ctx, req.(*SignUpBusiness))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetAccount(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Business)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/GetBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetBusiness(ctx, req.(*Business))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Business)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/UpdateBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateBusiness(ctx, req.(*Business))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_CreateOutlet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutlet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).CreateOutlet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/CreateOutlet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).CreateOutlet(ctx, req.(*CreateOutlet))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetOutlet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Outlet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetOutlet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/GetOutlet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetOutlet(ctx, req.(*Outlet))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateOutlet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Outlet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateOutlet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/UpdateOutlet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateOutlet(ctx, req.(*Outlet))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetOutletsByBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Business)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetOutletsByBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storeproto.StoreService/GetOutletsByBusiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetOutletsByBusiness(ctx, req.(*Business))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storeproto.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "signUp",
			Handler:    _StoreService_SignUp_Handler,
		},
		{
			MethodName: "getAccount",
			Handler:    _StoreService_GetAccount_Handler,
		},
		{
			MethodName: "getBusiness",
			Handler:    _StoreService_GetBusiness_Handler,
		},
		{
			MethodName: "updateBusiness",
			Handler:    _StoreService_UpdateBusiness_Handler,
		},
		{
			MethodName: "createOutlet",
			Handler:    _StoreService_CreateOutlet_Handler,
		},
		{
			MethodName: "getOutlet",
			Handler:    _StoreService_GetOutlet_Handler,
		},
		{
			MethodName: "updateOutlet",
			Handler:    _StoreService_UpdateOutlet_Handler,
		},
		{
			MethodName: "getOutletsByBusiness",
			Handler:    _StoreService_GetOutletsByBusiness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
